on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3.1.1
      with:
        ftp-server: sftp://${{ secrets.SERVER }}
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.PASSWORD }}
        git-ftp-args: --insecure
