on: push
name: Deploy website on push
jobs:
 upload_files:
    runs-on: ubuntu-latest
    name: Upload files.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.SERVER }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localPath: './root/'
        remotePath: './'
